[package]
name = "chimera-text"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.7", features = ["derive", "cargo"] }
epub = "2.1.2"
log = "0.4.21"
once_cell = "1.19.0"
serde = {version = "1.0.203", features = ["derive"]}
simplelog = "0.12.2"
